# Generated by Django 4.1.3 on 2022-11-06 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='list',
        ),
        migrations.AddField(
            model_name='list',
            name='movies',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movies.movie'),
            preserve_default=False,
        ),
    ]
