# Generated by Django 4.1.3 on 2022-11-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_list_list_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='movies',
        ),
        migrations.AddField(
            model_name='list',
            name='movies',
            field=models.ManyToManyField(related_name='movies', to='movies.movie'),
        ),
    ]
